services:
  - type: web
    name: finsense-ai
    env: python
    plan: free
    buildCommand: |
      . venv/bin/activate
      python health_server.py &
      rasa run actions --port 5055 &
      rasa run --enable-api --cors "*" --port 5005
    startCommand: |
      . venv/bin/activate
      rasa run actions --port 5055 &
      rasa run --enable-api --cors "*" --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.19
    healthCheckPath: /
